"""Create initial tables

Revision ID: 1ef1918c55f5
Revises: 
Create Date: 2022-06-27 22:19:08.378937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef1918c55f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection', sa.Text(), nullable=True),
    sa.Column('deterrent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pest_association',
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('pest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pest_id'], ['pests.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], )
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=10), nullable=True),
    sa.Column('indoor_months', sa.JSON(), nullable=True),
    sa.Column('outdoor_months', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('pest_association')
    op.drop_table('companions')
    op.drop_table('plants')
    op.drop_table('pests')
    # ### end Alembic commands ###
